In [1]:
# Q1
marks=int(input())
if(marks<=100):
    if(marks>=90):
        print("A")
    elif(marks>=75):
        print("B")
    elif(marks>=50):
        print("C")
    elif(marks>=0):
        print("Fail")
    else:
        print("invalid Input")
else:
    print("invalid Input")

 50


C


In [2]:
#Q2
num=int(input())
sum=0
while(num>0):
    sum+=num%10
    num=num//10
print("Sum of it's digit is : ",sum)

 123456


Sum of it's digit is :  21


In [3]:
#Q3
import math as mt
def is_prime(n):
    if(n<2):
        return False
    else:
        for i in range(2,int(mt.sqrt(n)+1)):
            if(n%i==0):
                return False
        return True

list=[10,123,42,3,2,-1,5,11,1]
for i in list:
    print(is_prime(i)," ")
    

False  
False  
False  
True  
True  
False  
True  
True  
False  


In [29]:
#Q4
def is_palindrome(word):
    return word==word[::-1]

list=["madam","adam","eye","computer","yes"]
for word in list:
    print(is_palindrome(word))
    

True
False
True
False
False


In [26]:
# Q5
import numpy as np
arr1=np.arange(1,10).reshape(3,3)
arr2=np.array([[1,10,2],[4,5,8],[9,6,2]])
print("Matrix A :\n",arr1)
print("Matrix B :\n",arr2)
print("Matrix Multiplication:\n",arr1.dot(arr2))
print("Determinant of Matrix B:\n",np.linalg.det(arr2))
inv=np.linalg.inv(arr2)
print("Inverse of Matrix B:\n",inv)
print("Verification:(Multiplying Inverse to original Matrix):\n",arr2.dot(inv))
print("Verdict: ",np.allclose(arr2.dot(inv),np.identity(3)))

Matrix A :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B :
 [[ 1 10  2]
 [ 4  5  8]
 [ 9  6  2]]
Matrix Multiplication:
 [[ 36  38  24]
 [ 78 101  60]
 [120 164  96]]
Determinant of Matrix B:
 559.9999999999999
Inverse of Matrix B:
 [[-6.78571429e-02 -1.42857143e-02  1.25000000e-01]
 [ 1.14285714e-01 -2.85714286e-02 -1.48690584e-18]
 [-3.75000000e-02  1.50000000e-01 -6.25000000e-02]]
Verification:(Multiplying Inverse to original Matrix):
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00  5.55111512e-17]
 [-6.93889390e-17  0.00000000e+00  1.00000000e+00]]
Verdict:  True


In [54]:
# Q6
from numpy import random
arr1=random.randint(1,10,10)
print(arr1)
arr2=random.randint(1,10,10)
print(arr2)
print("arr1 > arr2:", arr1 > arr2)
print("arr1 < arr2:", arr1 < arr2)
print("arr1 == arr2:", arr1 == arr2)
count_greater=np.sum(arr1>arr2)
print(count_greater)

[1 9 8 7 9 8 1 7 6 5]
[7 7 5 7 3 9 2 1 6 7]
arr1 > arr2: [False  True  True False  True False False  True False False]
arr1 < arr2: [ True False False False False  True  True False False  True]
arr1 == arr2: [False False False  True False False False False  True False]
4


In [74]:
#Q7
marks=[]
for i in range(10):
    marks.append(random.randint(0,101))
print("Marks: ",marks)
arr=np.array(marks)
print("Average :",arr.mean())
print("Marks above average:", arr[arr>arr.mean()])

Marks:  [19, 13, 62, 39, 87, 27, 65, 70, 90, 43]
Average : 51.5
Marks above average: [62 87 65 70 90]


In [85]:
#Q8
arr=np.arange(1,17).reshape(4,4)
print("Original :\n",arr)
print("Second Row:\n ",arr[1:2])
print("Third column:\n ",arr[:,2:3])
print("SubMatix 2x2 From Bottom Right:\n",arr[-2:,-2:])

Original :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Second Row:
  [[5 6 7 8]]
Third column:
  [[ 3]
 [ 7]
 [11]
 [15]]
SubMatix 2x2 From Bottom Right:
 [[11 12]
 [15 16]]


In [90]:
#Q9
arr=np.arange(1,13).reshape(3,4)
print("Original:(3x4)\n ",arr)
arr=arr.reshape(4,3)
print("Reshape:(4x3)\n ",arr)
arr=arr.ravel()
print("Ravel (Flats into 1D):\n",arr)

Original:(3x4)
  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshape:(4x3)
  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Ravel (Flats into 1D):
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [109]:
#Q10
sample = [random.randint(1, 7) for _ in range(1000)]
freq={}
print("Sample:\n",sample)
for i in range(1000):
    freq[sample[i]]=freq.get(sample[i],0)+1
print("Frequency of Rolling Dice:\n",freq)

Sample:
 [2, 3, 2, 6, 4, 5, 2, 4, 1, 3, 1, 4, 2, 2, 4, 3, 3, 5, 5, 3, 2, 4, 4, 6, 1, 2, 5, 4, 6, 6, 6, 2, 1, 4, 6, 3, 1, 6, 1, 5, 4, 5, 6, 1, 1, 6, 2, 4, 4, 5, 3, 2, 3, 1, 4, 1, 3, 4, 4, 4, 5, 2, 4, 5, 6, 2, 5, 4, 2, 5, 2, 3, 5, 2, 3, 3, 1, 6, 6, 5, 6, 1, 6, 6, 3, 4, 6, 1, 6, 6, 5, 1, 3, 6, 1, 1, 3, 6, 5, 3, 5, 1, 4, 6, 6, 5, 6, 5, 3, 6, 1, 5, 2, 1, 6, 2, 6, 6, 2, 5, 5, 6, 5, 1, 1, 3, 1, 6, 6, 3, 2, 4, 2, 2, 5, 5, 5, 1, 4, 2, 1, 3, 3, 1, 6, 2, 2, 3, 5, 6, 4, 5, 6, 2, 4, 2, 4, 4, 2, 6, 2, 3, 6, 2, 2, 4, 2, 6, 6, 3, 2, 2, 4, 5, 3, 3, 1, 1, 3, 5, 6, 2, 1, 2, 4, 4, 3, 4, 2, 2, 5, 2, 2, 3, 1, 3, 1, 2, 3, 1, 1, 4, 2, 2, 4, 6, 4, 6, 5, 4, 6, 1, 5, 1, 1, 4, 4, 1, 6, 5, 5, 4, 1, 4, 5, 6, 6, 1, 6, 3, 5, 1, 2, 5, 6, 4, 5, 2, 1, 6, 1, 1, 3, 6, 5, 5, 4, 2, 2, 5, 2, 6, 2, 4, 1, 3, 1, 6, 5, 4, 3, 3, 1, 1, 5, 5, 5, 1, 1, 6, 1, 5, 1, 1, 5, 5, 1, 2, 5, 3, 5, 1, 1, 6, 4, 5, 6, 1, 4, 5, 6, 3, 6, 5, 3, 1, 1, 1, 2, 6, 5, 1, 4, 1, 2, 2, 4, 1, 6, 1, 5, 1, 1, 4, 4, 4, 2, 4, 6, 4, 4, 6, 4, 5, 1, 5, 5, 6, 3, 6, 