In [8]:
#Creating 1D Array
import numpy as np

arr = np.array([10,20,30])

print("1D Array: ",arr)
print("Dimension(known as ndim): ",arr.ndim)
print("Shape of Array: ",arr.shape)
print("Size of Array: ",arr.size)

1D Array:  [10 20 30]
Dimension(known as ndim):  1
Shape of Array:  (3,)
Size of Array:  3


In [10]:
#Creating 2D Array
import numpy as np

arr=np.array([[1,2,3],[4,5,6]])

print("2D Array: \n",arr)
print("Dimension(known as ndim): ",arr.ndim)
print("Shape of Array: ",arr.shape)
print("Size of Array: ",arr.size)

2D Array: 
 [[1 2 3]
 [4 5 6]]
Dimension(known as ndim):  2
Shape of Array:  (2, 3)
Size of Array:  6


In [12]:
#Creating 2D Array
import numpy as np

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

print("2D Array: \n",arr)
print("Dimension(known as ndim): ",arr.ndim)
print("Shape of Array: ",arr.shape)
print("Size of Array: ",arr.size)

2D Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Dimension(known as ndim):  2
Shape of Array:  (3, 3)
Size of Array:  9


In [13]:
#Creating 3D Array
import numpy as np

arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print("3D Array: \n",arr)
print("Dimension(known as ndim): ",arr.ndim)
print("Shape of Array: ",arr.shape)
print("Size of Array: ",arr.size)

3D Array: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimension(known as ndim):  3
Shape of Array:  (2, 2, 2)
Size of Array:  8


In [20]:
#Creating 3D Array
import numpy as np

arr=np.array([[[1,2],[3,4],[10,20]],[[5,6],[7,8],[30,40]]])

print("3D Array: \n",arr)
print("Dimension(known as ndim): ",arr.ndim)
print("Shape of Array: ",arr.shape)
print("Size of Array: ",arr.size)

3D Array: 
 [[[ 1  2]
  [ 3  4]
  [10 20]]

 [[ 5  6]
  [ 7  8]
  [30 40]]]
Dimension(known as ndim):  3
Shape of Array:  (2, 3, 2)
Size of Array:  12


In [28]:
#Special Arrays
print("Zeros: \n",np.zeros((2,3)))
print("Ones: \n",np.ones((2,3)))
print("Empty (random memory values): \n",np.empty((2,4)))
print("Full: \n",np.full((2,3),56))
print("Identity Matrices (I): \n",np.identity(3))

Zeros: 
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Empty (random memory values): 
 [[4.9e-324 9.9e-324 1.5e-323 2.0e-323]
 [2.5e-323 3.0e-323 3.5e-323 4.0e-323]]
Full: 
 [[56 56 56]
 [56 56 56]]
Identity Matrices (I): 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
#Array Creation with Range
print("arange(0, 10, 2): ",np.arange(0,10,2))   #End element is not included & float values are not taken
print("linspace(0,1,5)", np.linspace(0,5,5))    #End element is included & Float values can be surely mostly taken

arange(0, 10, 2):  [0 2 4 6 8]
linspace(0,1,5) [0.   1.25 2.5  3.75 5.  ]


In [38]:
#Reshaped & Ravelled
import numpy as np

# Original 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the 1D array into 2D (2 rows, 3 columns)
reshaped_arr = arr.reshape(2, 3)
print("Reshaped array (2x3):")
print(reshaped_arr)
# Output:
# [[1 2 3]
#  [4 5 6]]

# Ravel the 2D array back to 1D
ravelled_arr = reshaped_arr.ravel()
print("\nRavelled array (1D):")
print(ravelled_arr)
# Output:
# [1 2 3 4 5 6]


Reshaped array (2x3):
[[1 2 3]
 [4 5 6]]

Ravelled array (1D):
[1 2 3 4 5 6]
