#**Lab Assignment on Chap 3**

###**Name: Arpit Kumar Mohanty**
###**Regd. No: 2341013237**
###**Serial Number: 31**

In [3]:
"""Q1. Data Holdout:
Load the dataset auto-mpg.csv and perform the following tasks:
1. Print the shape of the dataset.
2. Split the dataset into training (80%) and testing (20%) subsets.
3. Use a random state for reproducibility.
4. Print the training and test sets and their length"""

import pandas as pd
from sklearn.model_selection import train_test_split

data = pd.read_csv("auto_mpg.csv")
print("The Shape of the Data: ",data.shape)

train, test = train_test_split(data, test_size=0.2, random_state=42)

print("Training Dataset:\n",train)
print("Testing Dataset:\n",test)
print("Length of Training Dataset:\n",len(train))
print("Length of Testing Dataset:\n",len(test))

The Shape of the Data:  (398, 9)
Training Dataset:
       mpg  cylinders  displacement  horsepower  weight  acceleration  \
3    16.0          8         304.0       150.0  3433.0          12.0   
18   27.0          4          97.0        88.0  2130.0          14.5   
376  37.0          4          91.0        68.0  2025.0          18.2   
248  36.1          4          91.0        60.0  1800.0          16.4   
177  23.0          4         115.0        95.0  2694.0          15.0   
..    ...        ...           ...         ...     ...           ...   
71   19.0          3          70.0        97.0  2330.0          13.5   
106  12.0          8         350.0       180.0  4499.0          12.5   
270  21.1          4         134.0        95.0  2515.0          14.8   
348  37.7          4          89.0        62.0  2050.0          17.3   
102  26.0          4          97.0        46.0  1950.0          21.0   

     model_year  origin                   car_name  
3            70       1       

In [8]:
"""Q2. Implementing 5-Fold Cross-Validation
Using the dataset btissue.csv, do the following:
1. Create a 5-fold cross-validation.
2. For each fold (starting with 0), print:
 - fold number
 - indices of the training set
 - indices of the test set
3. Print the training set and test set and their length for the 3rd iteration."""

import pandas as pd
from sklearn.model_selection import KFold

data = pd.read_csv('btissue.csv')

kf = KFold(n_splits=5, shuffle=True, random_state=42)

for fold, (train_indices, test_indices) in enumerate(kf.split(data)):
    print(f"\n\nFold {fold}:")
    print("Training set indices:", train_indices)
    print("Test set indices:", test_indices)
    # for the 3rd iteration (fold 2)
    if fold == 2:
        train_data = data.iloc[train_indices]
        test_data = data.iloc[test_indices]
        print("\nTraining set for Fold 2:\n", train_data)
        print("\nTest set for Fold 2:\n", test_data)
        print("\nLength of Training set for Fold 2:", len(train_data))
        print("Length of Test set for Fold 2:", len(test_data),"\n")



Fold 0:
Training set indices: [  1   2   3   5   6   7   8   9  13  14  15  16  17  19  20  21  22  23
  24  25  26  27  28  29  31  32  34  35  36  37  38  39  40  41  43  45
  46  48  49  50  51  52  53  54  56  57  58  59  60  61  62  63  66  68
  69  70  71  72  73  74  75  76  77  82  83  84  85  86  87  88  89  90
  91  92  94  95  96  98  99 101 102 103 104 105]
Test set indices: [  0   4  10  11  12  18  30  33  42  44  47  55  64  65  67  78  79  80
  81  93  97 100]


Fold 1:
Training set indices: [  0   1   2   3   4   6   7   8  10  11  12  13  14  17  18  19  20  21
  23  24  25  27  29  30  32  33  34  37  38  41  42  43  44  46  47  48
  49  50  51  52  54  55  56  57  58  59  60  61  63  64  65  66  67  68
  69  70  71  72  74  75  78  79  80  81  82  83  84  85  86  87  89  90
  91  92  93  94  96  97  98  99 100 101 102 103 105]
Test set indices: [  5   9  15  16  22  26  28  31  35  36  39  40  45  53  62  73  76  77
  88  95 104]


Fold 2:
Training set indices: [ 

In [13]:
"""Q3. Bootstrap Sampling
With the dataset btissue.csv, perform the following:
1. Extract the predictors.
2. Generate a bootstrap sample of size 100.
3. Display the first 10 rows of the resampled data."""

import pandas as pd

data = pd.read_csv("btissue.csv")

# Extracting predictors (all columns except the last one which is the target variable)
predictors = data.iloc[:, :-1]

# Generate a bootstrap sample of size 100
# The replace=True argument is crucial for bootstrap sampling
bootstrap_sample = predictors.sample(n=100, replace=True, random_state=42)

# Displaying the first 10 rows of the resampled data
print("First 10 rows of the bootstrap sample:")
display(bootstrap_sample.head(10))

First 10 rows of the bootstrap sample:


I0     PA500       HFS           DA           Area        A/DA  \
102  2600.000000  0.200538  0.208043  1063.441427  174480.476200  164.071543   
51    274.993396  0.147131  0.137532    66.457943    1217.415651   18.318588   
92   1800.000000  0.091979  0.205251   362.863321   15021.553890   41.397278   
14    485.668806  0.230209  0.134041   253.893699    8135.968359   32.044783   
71   1385.664721  0.092328  0.089361   202.480044    8785.028733   43.387134   
60    197.000000  0.132645  0.074002    33.460653     409.647141   12.242652   
20    500.000000  0.192684  0.194779   144.688578    3055.012963   21.114403   
102  2600.000000  0.200538  0.208043  1063.441427  174480.476200  164.071543   
82   1647.939811  0.080983  0.086568   576.770376   11852.485060   20.549747   
86   2100.000000  0.121649  0.377689   450.551667   35671.606290   79.173176   

         Max IP          DR            P  
102  418.687286  977.552367  2664.583623  
51    40.849678   52.421008   327.558639  
92   217.833969  290.203640  1893.663712  
14    64.855446  245.470531   541.363975  
71   143.092194  143.257780  1524.609204  
60    26.992807   19.773813   231.783788  
20    96.563370  107.751103   542.897089  
102  418.687286  977.552367  2664.583623  
82   111.435913  565.902910  1402.877737  
86   436.099640  113.198570  2461.450497

In [15]:
"""Q4. Random Forest Classification and Evaluation
Using the dataset btissue.csv, carry out the steps below:
1. Separate predictors and target.
2. Perform a holdout split (80% training, 20% testing).
3. Train a Random Forest Classifier.
4. Evaluate the model using:
 - accuracy_score
 - confusion_matrix"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
# import joblib     # Import joblib to save the trained model

data = pd.read_csv('btissue.csv')

# 1. Separate predictors and target
predictors = data.iloc[:, :-1]  # All columns except the last one
target = data.iloc[:, -1]     # The last column

# 2. Perform a holdout split (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(predictors, target, test_size=0.2, random_state=90)

# 3. Train a Random Forest Classifier
rf = RandomForestClassifier(random_state=123)
rf.fit(X_train, y_train)

# 4. Evaluate the model
y_predicted = rf.predict(X_test)

print("Accuracy Score:", accuracy_score(y_test, y_predicted))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_predicted))

# 5. Save the trained model
# joblib.dump(rf, 'random_forest_model.pkl')
# print("\nTrained model saved as 'random_forest_model.pkl'")

Accuracy Score: 0.6363636363636364
Confusion Matrix:
 [[6 0 0 0 0 0]
 [0 1 0 0 0 1]
 [1 0 3 0 0 0]
 [0 0 0 0 2 2]
 [0 0 0 0 2 0]
 [0 0 0 1 1 2]]


In [17]:
"""Q5. Regression and Evaluation
Load the dataset auto_mpg.csv and perform the following tasks:
1. Remove all rows where value of any column is ‘NaN’.
2. Separate predictors and target.
3. Perform a holdout split (80% training, 20% testing).
4. Train a Linear Regression Model.
5. Evaluate the model using:
 - mean_squared_error
 - r2_score"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

data = pd.read_csv('auto_mpg.csv')

data = data.dropna(axis=0, how='any')
predictors = data.iloc[:,1:8]
target = data.iloc[:,0]
X_train, X_test, Y_train, Y_test = train_test_split(predictors, target, test_size = 0.25, random_state = 90)
model = LinearRegression().fit(X_train, Y_train)
Y_predicted = model.predict(X_test)
print("Mean Squared Error:",mean_squared_error(Y_test,Y_predicted))
print(r2_score(Y_test, Y_predicted))

Mean Squared Error: 12.066773327290973
0.8096337398502698


In [18]:
"""Q6. Clustering and Quality Measures
Using the dataset Dataset_spine.csv:
1. Exclude the class (last) column to form predictor variables.
2. Apply K-Means clustering with n_clusters=3 and random_state=123.
3. Compute and print:
 - v-measure score
 - Silhouette score"""

import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.metrics.cluster import v_measure_score
from sklearn.metrics import silhouette_score

data = pd.read_csv("Dataset_spine.csv")
# print(data)
data1 = data.iloc[:,:11]
# print(data1) # Kept commented as per original
data2 = data.iloc[:,12]

# FIX: Added n_init=10 to explicitly set the initialization runs
kmeans = KMeans(n_clusters=3, random_state=123, n_init="auto")
kmeans.fit(data1)
cluster_labels = kmeans.predict(data1)

v = v_measure_score(data2, cluster_labels)
s = silhouette_score(data1, cluster_labels, metric='euclidean', sample_size = 30)

print(f"V-Measure Score: {v}")
print(f"Silhouette Score: {s}")

V-Measure Score: 0.19950685588274256
Silhouette Score: 0.3344526592521278
