#***ML Lab's Minor Assignment on Chapter - 1***

###**Name: Arpit Kumar Mohanty**
###**Regd. No: 2341013237**
###**Serial Number: 31**

In [9]:
#Q1)
marks = int(input("Enter your Marks: "))
grade = ""
if(90<=marks<=100):
  grade = "A"
elif(75<=marks<=89):
  grade = "B"
elif(50<=marks<=74):
  grade = "C"
elif(0<=marks<=50):
  grade = "Fail"
else:
  grade = "Invalid Input"
print("Your Grade is: ",grade)

Enter your Marks: -10
Your Grade is:  Invalid Input


In [10]:
#Q2)
num = int(input("Enter your Number to be Caluclated Digit's Sum: "))
sum=0
while(num>0):
  sum = sum + (num%10)
  num = num//10
print("The Sum of the Digits are: ",sum)

Enter your Number to be Caluclated Digit's Sum: 234
The Sum of the Digits are:  9


In [55]:
#Q3)
import math as mt
import numpy as np
def isPrime(n):
  if(n>=2):
    for i in range(2,int(mt.sqrt(n))):
      if(n%i==0):
        return False
    return True
  else:
    return False
num = list(np.random.randint(1,70, size=7))
for items in num:
  print("Is Number {} prime: {}".format(items, isPrime(items)))

Is Number 4 prime: True
Is Number 62 prime: False
Is Number 25 prime: True
Is Number 33 prime: False
Is Number 11 prime: True
Is Number 46 prime: False
Is Number 65 prime: False


In [52]:
#Q4)
def isPalin(st):
  return st == st[::-1]
st = input("Enter your String: ")
print("Is your String %s Plaindrome (Case Sensitivly): %s" % (st,isPalin(st)))
print("Is your String %s Plaindrome (Ignoring Case Sensitivity): %s" % (st.lower(),isPalin(st.lower())))

Enter your String: Madam
Is your String Madam Plaindrome (Case Sensitivly): False
Is your String madam Plaindrome (Ignoring Case Sensitivity): True


In [23]:
#Q5)
import numpy as np
arr1=np.arange(1,10).reshape(3,3)
arr2=np.array([[1,6,4],[3,2,6],[4,10,3]])
print("Matrix A :\n",arr1)
print("Matrix B :\n",arr2)
print("Matrix Multiplication:\n",arr1.dot(arr2))
print("\nDeterminant of Matrix B:\n",np.linalg.det(arr2))
inv=np.linalg.inv(arr2)
print("\nInverse of Matrix B:\n",inv)
print("Verification: (Multiplying Inverse to original Matrix B) :\n",arr2.dot(inv))
print("Verdict: ",np.allclose(arr2.dot(inv),np.identity(3)))

Matrix A :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B :
 [[ 1  6  4]
 [ 3  2  6]
 [ 4 10  3]]
Matrix Multiplication:
 [[ 19  40  25]
 [ 43  94  64]
 [ 67 148 103]]

Determinant of Matrix B:
 124.00000000000003

Inverse of Matrix B:
 [[-0.43548387  0.17741935  0.22580645]
 [ 0.12096774 -0.10483871  0.0483871 ]
 [ 0.17741935  0.11290323 -0.12903226]]
Verification: (Multiplying Inverse to original Matrix B):
 [[ 1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00  1.11022302e-16]
 [-2.77555756e-17 -8.32667268e-17  1.00000000e+00]]
Verdict:  True


In [29]:
#Q6)
from numpy import random
ar1=random.randint(1,10,10)
print(ar1)
ar2=random.randint(1,10,10)
print(ar2)
print("\n1st Array > 2nd Array:", ar1 > ar2)
print("1st Array < 2nd Array:", ar1 < ar2)
print("1st Array == 2nd Array:", ar1 == ar2)
count_greater=np.sum(ar1>ar2)
print("\nThe Number of Elements greater than the 2nd Array is: ",count_greater)

[8 2 8 8 5 2 8 3 5 1]
[4 8 8 8 8 7 2 3 1 5]

1st Array > 2nd Array: [ True False False False False False  True False  True False]
1st Array < 2nd Array: [False  True False False  True  True False False False  True]
1st Array == 2nd Array: [False False  True  True False False False  True False False]

The Number of Elements greater than the 2nd Array is:  3


In [30]:
#Q7)
marks = []
for i in range(10):
    marks.append(random.randint(0,101))
print("Marks are: ",marks)
arr = np.array(marks)
print("Average scored is: ",arr.mean())
print("Marks which are above average: ", arr[arr>arr.mean()])

Marks are:  [58, 36, 84, 15, 88, 89, 18, 10, 10, 64]
Average scored is:  47.2
Marks which are above average:  [58 84 88 89 64]


In [38]:
#Q8)
arr = np.arange(1,17).reshape(4,4)
print("Original Matrix:\n",arr)
print("Second Row:\n ",arr[1:2])
print("Third column:\n ",arr[:,2:3])
print("Sub-Matix 2x2 From Bottom Right:\n",arr[-2:,-2:])    #We could also use arr[2:5,2:5]

Original Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Second Row:
  [[5 6 7 8]]
Third column:
  [[ 3]
 [ 7]
 [11]
 [15]]
Sub-Matix 2x2 From Bottom Right:
 [[11 12]
 [15 16]]


In [42]:
#Q9
arr=np.arange(1,13).reshape(3,4)
print("Original:(3x4)\n",arr)

print("Reshaping into (4x3):\n",arr.reshape(4,3))

print("Reshaping into (6x2):\n",arr.reshape(2,6))

print("Ravel (Flats into 1D):\n",arr.ravel())

Original:(3x4)
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaping into (4x3):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Reshaping into (6x2):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Ravel (Flats into 1D):
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [45]:
#10)
import numpy as np

sample = np.random.randint(1, 7, size=1000)

freq = {face: np.count_nonzero(sample == face) for face in range(1, 7)}

print("Sample Rolls:\n", sample)
print("\nFrequency of Rolling Dice:\n", freq)

Sample Rolls:
 [2 1 3 2 1 3 6 3 2 5 4 4 2 1 6 6 2 2 6 2 3 1 4 5 4 2 6 2 5 5 6 3 5 4 4 4 1
 3 6 3 4 2 4 2 1 6 5 2 3 5 4 6 3 5 1 5 3 2 6 3 3 1 4 3 1 6 6 3 2 5 1 1 1 5
 2 3 2 4 6 2 4 4 4 4 4 1 2 3 5 6 1 3 1 6 6 4 4 4 5 6 6 4 4 3 4 1 4 4 5 4 2
 2 5 5 4 5 2 5 3 5 5 6 6 4 2 4 1 4 6 2 5 5 3 2 4 2 3 3 2 2 5 1 5 5 1 3 3 1
 6 4 1 2 2 3 6 2 1 4 2 4 2 4 4 2 3 6 3 3 2 1 5 3 5 5 3 2 6 1 4 6 6 1 3 6 3
 2 4 5 2 5 5 2 6 1 5 2 4 4 4 6 3 4 6 6 5 6 6 5 2 5 2 4 3 6 2 4 5 4 3 2 5 2
 5 3 1 4 4 5 2 3 1 4 2 3 2 5 4 6 1 3 2 6 1 4 2 3 5 3 5 2 1 5 4 5 3 3 5 5 6
 3 5 4 3 6 5 4 4 4 4 5 5 2 5 5 2 3 2 3 4 2 3 3 5 2 5 5 5 5 2 1 5 2 1 4 5 6
 6 3 5 5 4 6 2 2 2 2 2 5 5 6 2 3 3 5 3 1 6 1 1 4 1 5 2 4 5 6 5 3 2 4 2 1 3
 3 1 1 1 5 3 3 4 3 4 3 6 1 6 4 3 4 1 5 3 1 3 5 2 4 6 2 5 1 4 5 1 2 5 1 3 1
 5 3 3 6 6 4 3 3 3 1 5 4 2 4 1 4 2 1 5 6 5 2 1 4 3 3 1 3 1 4 3 6 5 2 5 1 6
 4 4 4 1 1 3 2 5 1 4 4 2 3 6 2 4 3 1 5 5 4 6 2 2 2 3 1 4 6 4 1 5 1 4 6 5 5
 3 3 6 2 5 2 1 2 2 3 4 1 6 2 1 6 3 4 3 4 1 2 1 6 6 6 6 4 3 6 1 5 1 5 4 3 3
 4 5 3 2 2