In [19]:
import numpy as np
#arr = np.array([2,2,3])
arr = np.arange(24).reshape(4,6)
#arr1 = np.zeros(arr)
print(arr)

#arange gives only 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [24]:
arr2 = np.eye(3,4)
print(arr2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [43]:
arr = np.array([1.0,2,3,4,5.7])
arr1 = np.int64(arr)
arr2 = arr.astype(np.float64)
print(arr)
print(arr1)
print(arr2)                 

[1.  2.  3.  4.  5.7]
[1 2 3 4 5]
[1.  2.  3.  4.  5.7]


In [101]:
#Indexing & Slicing
#1D Array
# arr = np.arange(0,100,5)
# print(arr)
# print(arr[2:16:3])



# #2D Array
# arr = np.arange(0,100,5).reshape(4,5)
# print(arr)
# print(arr[0:2,2:4])

# arr = np.arange(1,5).reshape(2,2)
# print(arr)
# print(arr[0:1,0:1])



#3D Array
# arr = np.arange(0,100).reshape(4,5,5)
# print(arr)
# print("\nAfter Considering only 1st Matrix: ")
# print(arr[0:1])

# print("\nAfter Considering only 1st Row in all Matrix: ")
# print(arr[0:4,0:1,0:5])

# print("\nAfter Considering only 1st Coloumns in all Matrix: ")
# print(arr[0:4,0:5,0:1])

# print("\nAfter Considering only 4th Matrix: ")
# print(arr[0:4,0:2,0:2])

[[1 2]
 [3 4]]
[[1]]


In [116]:
# #Boolean Indexing 
# arr = np.arange(12)
# print(arr)
# indexes = [1,4,5]
# print(arr[indexes])

# #Copy after creating the Mask
# mask1 = arr%4==0                  #Creating the Multiples of 4
# print(mask)
# print(arr[mask])
# arr2 = arr.copy()

# mask2 = arr2%3==0
# print(mask2)
# arr2[mask2] =- 100
# print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[1 4 5]
[ True False False False  True False False False  True False False False]
[0 4 8]
[ True False False  True False False  True False False  True False False]
[-100    1    2 -100    4    5 -100    7    8 -100   10   11]


In [134]:
#Common Fucntions, (ufuncs)
arr = np.arange(14).reshape(2,7)
print(arr)

#1) Sqaure Root
arr_sq = np.sqrt(arr)
print(arr_sq)

#2) Sum
arr_sm = np.sum(arr)
print(arr_sm)

#3) Sum of Coloumns
arr_sm = np.sum(arr,0)
print(arr_sm)

#4) Sum of Rows
arr_sm = np.sum(arr,1)
print(arr_sm)

#5) Mean
arr_mean = np.mean(arr)
print(arr_mean)



#7) CUmulative Sum
arr_sm = np.cumsum(arr)        #Whole Sum
print(arr_sm)

arr_sm = np.cumsum(arr,axis=1)        #Coloumn wise Sum
print(arr_sm)

arr_sm = np.cumsum(arr,axis=0)        #Row wise Sum
print(arr_sm)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]
[[0.         1.         1.41421356 1.73205081 2.         2.23606798
  2.44948974]
 [2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
  3.60555128]]
91
[ 7  9 11 13 15 17 19]
[21 70]
6.5
[ 0  1  3  6 10 15 21 28 36 45 55 66 78 91]
[[ 0  1  3  6 10 15 21]
 [ 7 15 24 34 45 57 70]]
[[ 0  1  2  3  4  5  6]
 [ 7  9 11 13 15 17 19]]


In [150]:
#Linear Algebra
arr1 = np.arange(100)
arr2 = arr1.reshape(10,10)
print("1D Array: ",arr1)
print("2D Array: ",arr2)


x = np.linalg.det(arr2)
print(x)

1D Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
2D Array:  [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
0.0


In [159]:
#Random Numbers
rand_arr = arr.random((2,3))
print(rand_arr)

[[0.60663117 0.35927151 0.58900024]
 [0.26102558 0.03059563 0.59348585]]
