In [9]:

#Boolean Indexing and Function Copying

import numpy as np
m1 = np.arange(1,12)
index = [1,4,7]
print("Array: ",m1)
print("Indexes: ",index)
print("Choosen Indexes: ",m1[index])

#Masking a Masking Function 
mask = m1%3==0
print("\nMasked Number: ",mask)
print("Masked Numbers at Indexes: ",m1[mask])

#Copying A Function
m2 = m1.copy()
print("\n",m2)
print(m2%3==0)
m2[m2%3==0]=-1
print("After Replacing all the Numbers in Matrix 2: ",m2)




Array:  [ 1  2  3  4  5  6  7  8  9 10 11]
Indexes:  [1, 4, 7]
Choosen Indexes:  [2 5 8]

Masked Number:  [False False  True False False  True False False  True False False]
Masked Numbers at Indexes:  [3 6 9]

 [ 1  2  3  4  5  6  7  8  9 10 11]
[False False  True False False  True False False  True False False]
[ 1  2 -1  4  5 -1  7  8 -1 10 11]


In [37]:
#Inversing a Array using 

a1 = np.ones((3,3))
print("Original Singular Array: \n",a1)
print("Determinant of Original Singular Array: ",np.linalg.det(a1))
if (np.linalg.det(a1)):
    a2 = np.linalg.inv(a1)
    print("Inverse of Singular Array: \n",a2)
else:
    print("Inverse Doesn't Exists")
    
    
a2 = np.arange(1,10).reshape(3,3)
print("\nOriginal 2nd Array: \n",a2)
print("Determinant of 2nd Array: ",np.linalg.det(a2))
a2 = np.linalg.inv(a2)
print("Inverse of 2nd Array: \n",a2)

#Random Integer Generation and shaping them into the Matrix
a4 = np.random.randint(5,15, size=(2,3,3))
print("1st Method: \n",a4)
a5 = np.random.randint(5,15,12).reshape(3,4)
print("2nd Method: \n",a5)

Original Singular Array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Determinant of Original Singular Array:  0.0
Inverse Doesn't Exists

Original 2nd Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinant of 2nd Array:  -9.51619735392994e-16
Inverse of 2nd Array: 
 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
1st Method: 
 [[[12 13 11]
  [10  7 10]
  [10  6 10]]

 [[11  7  6]
  [ 9  8  8]
  [ 8  9  5]]]
2nd Method: 
 [[ 9  7 13 12]
 [ 7  7  9  5]
 [ 8  9 11  5]]
