In [5]:
#Q1) WAP for Fibonacci Series by using Recursive Function.  
# Star Pattern aslike Center domed Pyramid using while loop.
# Factorial by using the Function

#FIBONACCI
# def fib(n):
#     if (n==1 or n==2):
#         return 1
#     else:
#         return fib(n-1) + fib(n-2)
# print("The 1st 5 Numbers of Fibnacci Series after 1: ")
# for i in range(1,6):
#     print(fib(i),end = " ")

#FACTORIAL
# def fac(num):
#     if(num==0 or num==1):
#         return 1
#     else:
#         return num*fac(num-1)
# print("Factorial of 5 is: ",fac(5))

#Pattern
inp = int(input("Enter the Number of Lines you want to see in the Pattern: "))
sp = inp-1
for i in range(1,inp+1):
    print(" "*sp+"*"*(2*i-1))
    sp = sp-1

Enter the Number of Lines you want to see in the Pattern: 7
      *
     ***
    *****
   *******
  *********
 ***********
*************


In [28]:
#Q2) Construct 3D Array in 10 ways
import numpy as np
a1 = np.arange(1,51).reshape(2,5,5)
print(a1)
a2= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]).reshape(3,2,3)
print(a2)
a3 = np.linspace(1,19,18).reshape(3,2,3)
print(a3)
a4 = np.zeros((2,2,2))
print(a4)
a5 = np.ones((3,3,3))
print(a5)
a6 = np.full((2,2,2),7)
print(a6)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]
  [21 22 23 24 25]]

 [[26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]
  [41 42 43 44 45]
  [46 47 48 49 50]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
[[[ 1.          2.05882353  3.11764706]
  [ 4.17647059  5.23529412  6.29411765]]

 [[ 7.35294118  8.41176471  9.47058824]
  [10.52941176 11.58823529 12.64705882]]

 [[13.70588235 14.76470588 15.82352941]
  [16.88235294 17.94117647 19.        ]]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[[7 7]
  [7 7]]

 [[7 7]
  [7 7]]]


In [ ]:
#Q3) Why set is not considered in the Series Creation of Panda Library
#Answer -> Set cannot be constructed using the Series cuz it's immutable and has unordered set of elements
#(which doesn't follows any indexes) so basically for using set we can convert the set into list[MOST BASIC]

In [17]:
#Q4) Why numpy, 2D array and 3D Array is considered as object type in pandas Library.
#Show series Creation for dictionary and tuple
#Answer -> Panda mostly take series or linear types of inputs but it doesn't associates numpy to be in a series format as it
#is used to create arrays, matrices and for 2D and 3D arrays its not linear type of data structures therefore it 
# can't be used along with the Pandas

import pandas as pd
tu = (1,2,3,4,5)
dic = {
    1: 'a',
    2: 'b',
    3: 'c',
    4: 'd',
    5: 'e'
}

print("Tuple as in series:\nn",pd.Series(tu))
print("Dictionary as in series:\n",pd.Series(dic))

Tuple as in series:
n 0    1
1    2
2    3
3    4
4    5
dtype: int64
Dictionary as in series:
 1    a
2    b
3    c
4    d
5    e
dtype: object


In [ ]:
#Q5) Calulate the inverse and Solve the matrices provided by the user
a = [int(n) for n in input("Enter the rows and cols of matrix: ").split()]
ar = []
print(a,b)

In [ ]:
#Q5) Calulate the inverse and Solve the matrices provided by the user
a = int(input("Enter the rows: "))
b = int(input("Enter the Coloumns: "))
print(a,b)
ar = []
if(a==b):
    for i in range(0,a):
        l = [int(x) for x in input("Enter elements in rows: ").split()]
        ar.append(l)
    arr = np.array(ar)
    deter = np.linalg.det(arr)
    if (deter != 0):
        print("Determinant is: ",deter)
        print("Inverse Exists and it is: ",np.linalg.inv(arr))
    else:
        print("Its a singular Matrix whose determinant is 0")
else:
    print("Determinant cannot be calculated if rows are not equal to coloumns")